import React, { FC, useState } from 'react';

import Info from '../components/Cards/Info';
import Inventory from '../components/Cards/InventoryTable';

//Configuration is auto generated by YML script inside craco.config.js

interface HomeProps {
  mobileCheck(): boolean;
}

const Home: FC<HomeProps> = ({ mobileCheck }) => {
  const [accountInventory, setAccountInventory] = useState(0);
  const [repricedToday, setRepricedToday] = useState(0);
  const [repricedThisWeek, setRepricedThisWeek] = useState(0);
  const [repricedThisMonth, setRepricedThisMonth] = useState(0);
  return (
    <>
      <div className='flex items-center justify-center'>
        <div className='w-full md:w-4/5 xl:w-3/5 mx-auto px-2'>
          <div className='container'>test</div>
        </div>
      </div>
    </>
  );
};

export default Home;
