import React, { FC } from "react";

//Configuration is auto generated by YML script inside craco.config.js
import conf from "../config/vidoesConfiguration.json";

import Settings from "../components/Cards/Settings";
import Info from "../components/Cards/Info";

const { SethIntro, SleepMonitor } = conf;

interface HomeProps {
  mobileCheck(): boolean;
}

const Home: FC<HomeProps> = ({ mobileCheck }) => {
  return (
    <div>
      <div className="container">
        <div className="flex justify-center pt-8 ml-0">
          <Info
            inactiveText="Inactive"
            title="Acount Status"
            inactiveTextClass="font-bold text-3xl text-red-600"
            activeTextClass="font-bold text-3xl text-green-600"
            activeText="Active"
          />
          <Info
            active={false}
            inactiveText="Inactive"
            title="API Connected"
            inactiveTextClass="font-bold text-3xl text-red-600"
            activeTextClass="font-bold text-3xl text-green-600"
            activeText="Active"
          />
          <Info title="Need Help?" activeText="support@nuprice.co" />
        </div>
      </div>

      <div className="flex justify-center px-3">
        <Settings />
      </div>
    </div>
  );
};

export default Home;
