import React, { FC } from "react";

//Configuration is auto generated by YML script inside craco.config.js
import conf from "../config/vidoesConfiguration.json";

import Input from "../components/Inputs/Basic";

const { SethIntro, SleepMonitor } = conf;

interface HomeProps {
  mobileCheck(): boolean;
}

const Home: FC<HomeProps> = ({ mobileCheck }) => {
  return (
    <div className="content-center h-screen flex-wrap">
      <div className="h-1/6"></div>
      <h1 className="text-5xl pb-14 text-center font-bold font-sans">
        Sign Up Here
      </h1>
      <form className="px-10 py-5 md:m-auto lg:m-auto md:w-5/12 lg:w-3/12 xlg:w-2/12 mx-10">
        <Input label="Username" id="username" />
        <Input label="Password" type="password" id="password" />
        <Input label="Confirm password" type="password" id="confrimPassword" />
        <Input label="License Key" id="key" />

        <div className="flex justify-between">
          <a href="https://gumroad.com" className="w-1/2 py-6 text-gray-400">
            Need a License Key?
          </a>

          <input
            className="my-5 w-full bg-primary uppercase hover:bg-primaryLight text-white font-bold py-2 px-4 mb-6 rounded cursor-pointer"
            type="submit"
            name="Login"
            value="Sign Up"
          />
        </div>
      </form>
    </div>
  );
};

export default Home;
