Brand:
  src: img/logo1.webp
  height: 64
  width: 180
  alt: BioFi

Links:
  - name: Our Tech
    link: '/tech'
    component: OurTech

  - name: About
    link: '/about'

  - name: Team
    link: '/team'

  - name: Contact Us
    link: '/contact'
    component: Contact
