Members:
  - name: Seth Campbell
    titleRank: 1
    title: CEO
    img: img/team/Seth_Campbell_600x600.webp
    accomplishments:
      - Became Entrepreneur at Age 24
      - Has Generated $10+ Million/Year for 8 Years
      - Has Spoken at Events Worldwide on Entrepreneurship Including TedX & John C. Maxwell Events
      - Over a Decade Spent Building a Network of Business Leaders
    bio:
      Seth has been a business and network builder for 11 years. He has built a large multi national sales organization, and served on the advisory board for a $200M publicly traded biotech company.
      He has also been a public speaker and trainer on business and entrepreneurialism, speaking at events across the globe including appearing in a John C. Maxwell training series and being a TedX presenter.
    categories:
      - Management
      - Board
      - Founder
  - name: Giangi Sacco
    titleRank: 2
    title: CTO
    img: img/team/Giangi_Sacco_600x600.webp
    accomplishments:
      - PhD in Physics from University of Connecticut
      - Data Scientist at NASA JPL
      - Developer of Deep Learning Models to Radar Imagery for over 5 years
      - Scientific Algorithm Developer for over 15 years
      - Member of the Science Data System Architect Team on Multiple NASA Missions
    bio:
      Giangi Sacco is a data scientist in the Science Data Modeling and Computing (SDMC) group in the Instrument Software and Science Data System Section at the Jet Propulsion Laboratory. He received a B.S. in theoretical nuclear physics for university of Turin, Italy and a M.S. and Ph.D. in theoretical high energy physics from the University of Connecticut.
      He joined the SDMC group in December 2004 at first as National Research Council post doctoral fellow and later as NASA post doctoral fellow conducting research on optical properties and spin manipulation of Silicon quantum dots and fault tolerant high performance computing in space. He became a permanent member of the SDMC in December 2006.
      Since joining JPL he covered a vast range of fields spanning from physics, framework development for scientific applications, atmospheric radar algorithm, to machine learning for earth science. His main focus in the past few years at JPL have been cloud-based Science Data Systems and machine learning. In 2017 he became a co-founder of Praesidium Inc. where he currently is working on applying machine learning techniques and digital signal processing algorithm to our products. Since late 2019 Giangi moved to a part-time position at JPL to dedicate more time to Praesidium and combine his love for science and the opportunity to apply technology to improve the quality of life of many people which is the company mission.
      In his (very limited) spare time he enjoys mountain biking, hiking, practicing martial arts, yoga and fitness in general. He is also an amateur (and untalented) flamenco and classical guitar player.
    categories:
      - Management
      - Engineer
      - Founder
  - name: Paolo Focardi
    titleRank: 5
    title: RF Engineer
    img: img/team/Paolo_Focardi_600x600.webp
    accomplishments:
      - PhD in Computer Science from University of Florence
      - Senior RF Microwave Engineer at NASA JPL
      - Over 20 years experience in Electromagnetic’s
      - Leading hardware & software R&D on remote sensing of vital signs since 2004
    bio:
      I developed and delivered the Feed Horn Assembly for SMAP, the first scientific flight project to use a deployable mesh reflector and was responsible for radiation pattern calculations including the effect of the entire spacecraft.
      I have been responsible for the development of the RF front end needed for the "Remote Sensing of Human Vital Signs" project. Several planar antennas and directional couplers have been designed, fabricated and tested. I supervised the measurement of radiation pattern and scattering parameters of the antennas under development. I also collaborated with Tanner Labs at the development of THz detectors for a two year project funded by the Air Force entitled "Multispectral Imaging with a Plasmon Lens".
      I have been supporting the development of the A1 and A2 antennas for JUNO. After that I joined the RF team developing the reflector antenna for SMAP. I am also the JPL PI of a project entitled "A room temperature Tunable Antenna Coupled Intersubband Terahertz (TACIT) detector for man portable spectroscopy instruments" in collaboration with Tanner Labs and UCSB.
    categories:
      - Management
      - Board
      - Founder

  - name: Tyler Daniels
    titleRank: 6
    title: Founder
    img: img/team/Tyler_Daniels_600x600.webp
    accomplishments:
      - 4 Years USAF
      - 7 Years Real Estate Appraiser
      - 17 Years Owner Retirement Options Inc
      - Original Praesidium Investor Group
    bio:
      Has organized a sales/distribution network currently supporting in excess of $10M/mo - $100M/yr with total global sales in excess of $1B.
      Global developer/advisor/marketing consultant with over 10 years experience on advisory boards/advisory committees which includes Lifevantage Corp a publicly traded NASDAQ company focused on health and wellness.
    categories:
      - Board
      - Founder

  - name: Skip Campbell
    titleRank: 6
    title: Founder
    img: img/team/Skip_Campbell_600x600.webp
    accomplishments:
      - 4 Years USAF
      - 20 years in practice as a Doctor of Chiropractic, Parker, CO
      - Co-taught a complementary and alternative medical elective University of Colorado
      - 12 yrs Owner and Ceo of Protential Freedom, a marketing company
      - Original Praesidium Investor Group
    bio:
      Has organized a sales/distribution network currently supporting in excess of $2.5M/mo - $30M/yr with global sales in excess of 200M.
      Global developer/advisor/marketing consultant with over 10 years experience on advisory boards/advisory committees which includes Lifevantage Corp a publicly traded NASDAQ company focused on health and wellness.

    categories:
      - Founder

  - name: Mick Zoltan
    titleRank: 8
    title: Embedded Engineer
    img: img/team/Mick_Zoltan_520x520.webp
    accomplishments:
      - Developed an interest in electronics at the age of 6
      - Built his first detector radio at the age of 9
      - Gravitated to digital electronics and software engineering at 14
      - Coded his first game at 19
      - Started a 'new' life in the US at 24
    bio:
      "Miklos has been a technology enthusiast, perpetual learner, and inventor in the embedded and RF engineering fields for over three decades. After less than a year in the land of the free, he joined a startup - Lighting Control & Design – as hardware and firmware engineer and became a key player helping the organization grow to acquisition.
      In his free time, he studies nanotechnology, particle physics, and thinkers with his GUT (Grand Unification Theory – no pun intended).
      His Philosophy (and I quote): “I consider every day an opportunity to learn something new. Since we can't learn what we think we already know, it is vital to systematically separate the known from the unknown. While this is obvious to most, it is easier said than done. Many factors can cause one to lose sight which is why I think it is vital to work on our ability to remain focused on facts.” "
    categories:
      - Engineer

  - name: Chad Koslovsky
    titleRank: 7
    title: Fullstack Engineer
    img: img/team/Chad_Koslovsky.webp
    imgAlt: img/team/Chad_Koslovsky_600x600.webp
    social:
      github: https://github.com/Ravonus
      linkedin: https://www.linkedin.com/in/chadkoslovsky/
    accomplishments:
      - built this website.
      - is part robot.
      - found the Matrix.
    bio: He is a robot. Is there really any more that needs to be said?
    categories:
      - Engineer
  - name: Paul Langlois
    titleRank: 3
    title: CFO
    accomplishments:
      - BS & Masters in Accounting, AA in Engineering & Technology
      - Certified Public Accountant (Colorado)
      - 12+ years’ experience in Accounting, Finance, and Tax
      - Was a member of the finance team for companies such as PwC, The Western Union Company, Empower Retirement, and OppenheimerFunds
    bio:
      Paul began his professional career over 12 years ago and has held increasing finance roles responsible for federal & state compliance & tax controversy in addition to tax accounting (Statutory & GAAP) for corporate & life-insurance finance functions.
      His roles involved working within finance to build corporate value, protect corporate assets, and comply with financial regulatory requirements.
      As the CFO of Praesidium, Inc., his responsibilities include various finance capacities, including, accounting, tax, payroll, accounts payable, and in an advisory role for any other financial/legal matters.
    img: img/team/Paul_Langlois_600x600.webp
    categories:
      - Management

  - name: Michael Breus
    titleRank: 4
    title: CSO
    img: img/team/Michael_Breus_600x600.webp
    accoplishments:
      - Double board certified in clinical psychology and sleep disorders
      - Youngest to have passed the board without going to medical school
      - 15 years sleep expert for WedMD
      - 100’s of television appearances including 39 on Dr. Oz
      - Completes over 200 interviews a year
    bio:
      Among his numerous national media appearances, Dr. Breus has been interviewed on CNN, Oprah, The View, Anderson Cooper, Rachel Ray, Fox and Friends, The Doctors, Joy Behar, The CBS Early Show, The Today Show, and Kelly and Michael.
      He is an expert resource for most major publications doing more than 200 interviews per year (WSJ, NYT, Washington Post, and most popular magazines). He also appears regularly on Dr. OZ and Sirius XM Radio.
    categories:
      - Management

  - name: Jim Atwell
    title: Advisor - Investor
    img: img/team/Jim_Atwell_600x600.webp
    accomplishments:
      - Founding Partner in 235 Capital Partners
      - Former managing partner at Deloitte where he led the technology industry practice
      - Has completed over 60 successful IPO’s
    bio:
      Jim has more than 30 years of experience providing audit and financial consulting services to technology companies in the public and private sectors.
      He is the National Managing Partner of both the Technology, Media and Telecommunications industry practice and the Emerging Growth Company practice of Deloitte & Touche LLP.
      Jim is responsible for the firm’s audit growth strategy, and leads the teams responsible for providing services to public and rapidly growing private companies.
      He has served numerous public companies, such as Cisco Systems, eBay, FireEye, Penumbra, Polycom, Rambus, Solera Holdings, SoftBank Group, Sony, and Toshiba.
    categories:
      - Board
      - Advisor

  - name: Dave Bolen
    title: Investor - Board Member
    img: img/team/Dave_Bolen_600x600.webp
    accoplishments:
      - 30 Years Of Senior Leadership
      - Senior Position At Perot Systems
      - Senior Position At Dell Services
      - Senior Position At NTT Data Services
    bio:
      Dave has been serving in senior leadership positions in the technology industry for the last 30 years.
      Starting his career in business and technology consulting and moving into delivery, operations and sales leadership, he has been responsible for over 4B in top-line growth and consistent year over year margin improvement in the Managed Services industry.
      Dave has held senior positions with Perot Systems, Dell Services and NTT Data Services as well as several small business ventures.
      Dave brings a wealth of knowledge across the Telecom, Media, Entertainment, Retail, CPG, Travel, Hospitality and Real Estate industries.
    categories:
      - Board
      - Investor
